spring:
  redis:
    #redis密码
    password: ql1234
    # 单机配置host和port参数
    host: 47.100.173.179
    port: 6379
      # 哨兵配置
      #sentinel:
    #  master: mymaster
    #  nodes: 47.100.173.179:26379,47.100.173.179:26378,47.100.173.179:26377
    # cluster集群配置
    #    cluster:
    #      nodes:
    #        - 47.100.173.179:6800
    #        - 47.100.173.179:6801
    #        - 47.100.173.179:6802
    #        - 121.89.200.198:6800
    #        - 121.89.200.198:6801
    #        - 121.89.200.198:6802
    #      max-redirects: 3
    lettuce:
      pool:
        max-active: 16 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 16  #连接池中的最大空闲连接
        min-idle: 16 #连接池中的最小空闲连接

