server:
  port: 8888

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev,redis
  application:
    name: @artifactId@
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: iflash
    url: jdbc:mysql://styn-mysql:3306/swine_main?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #password:

# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: false
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: sys_
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置slq打印日志

# 分布式定时任务xxl-job配置
xxl:
  job:
    admin:
      addresses: http://styn-xxl-job-admin:9350/xxl-job-admin

