#  切记： 首先要开启 数据库数据同步功能   mysql： 开启mysql-binlog日志   mysql开启主从同步配置：https://www.cnblogs.com/songwenjie/p/9371422.html
#        配置过程中可能会出现一些问题 ，细心查看     其中一个问题的解决方案 ： https://blog.csdn.net/weixin_37998647/article/details/79950133
#sharding-jdbcReadWrite 实现读写分离的配置 master/slave   master 主要写数据   slave实现读数据  这是sharding-jdbc 通过执行的sql 来判断的
spring:
  main:
    # 当遇到同一个实体类同时映射多个相同的表名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true
  shardingsphere:
    # 配置多个数据源
    datasource:
      names: ds-master,ds-slave0
      ds-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url:  jdbc:mysql://47.100.173.179:3306/ds_master0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password:  qinlei131479@QQ!!
        initial-size: 4 # 初始化时建立物理连接的个数
        min-idle: 1   # 最小连接池数量
        max-active: 40 #  最大连接数量
        query-timeout: 60000 #查询超时
        filters: stat,config # stat表示sql合并
        testOnBorrow: false  # 申请连接时执行validationQuery检测连接是否有效
      ds-slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://121.89.200.198:3306/ds_master0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qinlei131479@QQ!!
        initial-size: 4 # 初始化时建立物理连接的个数
        min-idle: 1   # 最小连接池数量
        max-active: 40 #  最大连接数量
        query-timeout: 60000 #查询超时
        filters: stat,config # stat表示sql合并
        testOnBorrow: false  # 申请连接时执行validationQuery检测连接是否有效

      # 配置读写分离规则
    masterslave:
      name: ds-ms #规则名称
      master-data-source-name:  ds-master  #主库 多个逗号隔开
      slave-data-source-names:   ds-slave0   # 从库 多个逗号隔开 ds_slave0,ds_slave1  多个从库 读时采用 下面的配置方式读数据
      loadBalanceAlgorithmType:  ROUND_ROBIN          #从库负载均衡算法类型，可选值：ROUND_ROBIN，RANDOM。(循环/随机) 若`loadBalanceAlgorithmClassName`存在则忽略该配置

    props:
      sql.show: true  #   显示sql




