# 系统配置
spring:
  application:
    name: @artifactId@
  profiles:
    # readWrite 只有读写分离 jdbc 只有分库分表配置  jdbcAndReadWrite 读写分离和分库分表配合使用 single 单库单表
    active: jdbcAndReadWrite
  freemarker:
    check-template-location: false

server:
  # 端口
  port: 8084
  # 访问路径
  servlet:
    context-path: /share

#mybatis 配置
mybatis-plus:
  #  xml存放地址
  mapper-locations: classpath:/mappers/*.xml
  global-config:
    # 关闭图标
    banner: false
    db-config:
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 表前缀
      table-prefix: tb_
  configuration:
    map-underscore-to-camel-case: true
    # 可以参考生产环境可以注释掉该项（打印sql执行日志）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

